---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.(conf|j2|js|json|rb|md|py|sh|tf|tm?pl|txt|yaml|yml)$
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '^(\.idea/.*|password_.*|src/test/resources/test)$'
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          - '--baseline'
          - '.secrets.baseline'
        exclude: 'package-lock\.json$|Pipfile\.lock$|poetry\.lock$|^.secrets.baseline$'
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        exclude: 'gradlew|mvnw$'
      - id: shfmt
        exclude: 'gradlew|mvnw$'
        args:
          - '-i 2 -ci -bn -sr'
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.2
    hooks:
      - id: editorconfig-checker-system
        alias: ec
